# Generated by Django 4.1 on 2022-08-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
