# Generated by Django 4.1 on 2022-08-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Equipment ID')),
                ('description_1', models.CharField(max_length=30, verbose_name='Description')),
                ('description2', models.CharField(max_length=255, verbose_name='Description 2')),
                ('description3', models.CharField(max_length=255, verbose_name='Description 3')),
                ('serial', models.CharField(max_length=255, verbose_name='Serial')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('model_year', models.IntegerField(verbose_name='Year')),
                ('status_code', models.IntegerField(verbose_name='Status')),
                ('department', models.IntegerField(verbose_name='Department')),
                ('item_class', models.IntegerField(verbose_name='Class')),
                ('job_number', models.CharField(max_length=255, verbose_name='Job Number')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Warehouse')),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.company')),
                ('division_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.division')),
            ],
        ),
    ]
