# Generated by Django 4.1 on 2022-08-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='job_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Number'),
        ),
    ]
