# Generated by Django 4.1 on 2022-08-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_division_company_id'),
        ('equipment', '0004_alter_equipment_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.company'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='division_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.division'),
        ),
    ]
