# Generated by Django 4.1 on 2022-08-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_division_company_id'),
        ('equipment', '0003_alter_equipment_job_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_status', models.IntegerField(blank=True, null=True)),
                ('ask_date', models.DateTimeField(blank=True, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.equipment')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.company')),
                ('to_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.division')),
            ],
        ),
    ]
