# Generated by Django 4.1 on 2022-08-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_status_alter_equipment_company_id_and_more'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='id',
        ),
        migrations.AlterField(
            model_name='transfers',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='equipment.equipment'),
        ),
    ]
