# Generated by Django 4.1 on 2022-09-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_division_company_id"),
        ("transfers", "0005_transferhistory_transfer_history_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfers",
            name="from_company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_company",
                to="profiles.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfers",
            name="from_division",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_division",
                to="profiles.division",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfers",
            name="from_status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transfers",
            name="to_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_company",
                to="profiles.company",
            ),
        ),
        migrations.AlterField(
            model_name="transfers",
            name="to_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_division",
                to="profiles.division",
            ),
        ),
    ]
