# Generated by Django 4.1 on 2022-09-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_division_company_id"),
        ("transfers", "0006_transfers_from_company_transfers_from_division_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferhistory",
            name="from_company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_history_from_company",
                to="profiles.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="from_division",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_history_from_division",
                to="profiles.division",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="from_status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transferhistory",
            name="to_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_history_to_company",
                to="profiles.company",
            ),
        ),
        migrations.AlterField(
            model_name="transferhistory",
            name="to_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_history_to_division",
                to="profiles.division",
            ),
        ),
        migrations.AlterField(
            model_name="transfers",
            name="from_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_from_company",
                to="profiles.company",
            ),
        ),
        migrations.AlterField(
            model_name="transfers",
            name="from_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_from_division",
                to="profiles.division",
            ),
        ),
        migrations.AlterField(
            model_name="transfers",
            name="to_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_to_company",
                to="profiles.company",
            ),
        ),
        migrations.AlterField(
            model_name="transfers",
            name="to_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_to_division",
                to="profiles.division",
            ),
        ),
    ]
